baseURL = 'https://slainbynetflix.com'
languageCode = 'en-us'
title = 'Slain by Netflix'
theme = 'lugo'

[params]
  logo = '/img/logo.png'
  mainSections = 'movies'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about hugo'
  url = '/about/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'